name: Build
on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]
        include:
          - os: windows-2019
            name: windows
          - os: ubuntu-18.04
            name: linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure CMake
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        working-directory: ./build
        shell: bash
        run: cmake --build . --config Release
      - name: Prepare to upload artifact
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir artifact
          if [ "$RUNNER_OS" == "Windows" ]; then
            cp ./build/bin/Release/make-all-settings-in-quick-settings-persistent.dll artifact/
          else
            cp ./build/bin/Release/make-all-settings-in-quick-settings-persistent.so artifact/
          fi
          cp license.txt artifact/
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{matrix.name}}
          path: artifact
